### ISSUE TITLE
[vscode] `.clj-kondo/config.edn` is not picked up in a multi-folders workspace

### ISSUE THREAD

**Issue by gjeanmart** [borkdude/clj-kondo.lsp#7]
Hi,

I just noticed my `.clj-kondo/config.edn` isn't picked up by clj-kondo in vscode if:
- I have a multi-folders workspace
- The first folder added to the workspace doesn't have a `.clj-kondo/config.edn` 

Basically it sounds like the first folder is setting the rules for all the workspace.

Thanks

**Comment by borkdude** [comment]
@gjeanmart clj-kondo uses the current working directory to determine the .clj-kondo directory. So whatever VSCode sets as current working directory, that directory is searched upwards to the root for a .clj-kondo directory. Does that make sense?

**Comment by gjeanmart** [comment]
Hi @borkdude 
Thanks for your answer, yeah that makes sense and would work 99% of the time I guess. Only problem I see is when someone has a [Multi-root Workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces), as per my understanding, the current working directory set is the first "project", but adding a second Clojure project (_add new folder_) would be ruled by the first project clj-condo config.
If I'm right, I think that's an edge case.

**Comment by borkdude** [comment]
@gjeanmart We had an option in clj-kondo before when both the current working directory AND the parent directory of the file were used starting points for finding the .clj-kondo directory. That would be a solution for this problem maybe, if we introduced that again. Do you think the 1% case is worth this change?

**Comment by gjeanmart** [comment]
From my point of view, no, because I only want to have two projects in my workspace and one of them has a clj-kondo config. So in my case, I only had to add the project with .clj-kondo first to fix my issue and the fact the second project is ruled by that file isn't a problem.

At least, if someone tries to understand why his clj-kondo config isn't picked up, the behavior is clear and the answer here.

Feel free to close.
