### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by holyjak** [borkdude/clj-kondo.lsp#8]
- Issue Type: `Performance`
- Extension Name: `clj-kondo`
- Extension Version: `2020.5.90`
- OS Version: `Darwin x64 19.5.0`
- VSCode version: `1.46.0`

Profile:
[borkdude.clj-kondo-unresponsive.cpuprofile.txt](https://github.com/borkdude/clj-kondo.lsp/files/4769205/borkdude.clj-kondo-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by borkdude** [comment]
Diagnostics in https://github.com/BetterThanTomorrow/calva/issues/667

**Comment by PEZ** [comment]
Turns out this was not from this extension, but from Calva. So probably should be closed?

**Comment by borkdude** [comment]
More than glad to!
